### ISSUE TITLE
An error occurred while executing the ribodetector_cpu command.

### ISSUE THREAD

**Issue by kinako0130** [hzi-bifo/RiboDetector#55]
Hi, I encountered the following error.
Is there a solution for this?
I have tried using RiboDetector versions 0.3.1 and 0.3.0 installed via Conda.
Additionally, I tested it with Python versions 3.8.0 and 3.8.20.

Thank you in advance for your help.

### Input command
`ribodetector_cpu -t 20 -l 100 -i /datafilepath/SRR22266027_1_qc20.fastq  -e norrna  --chunk_size 256  -o /datafilepath/SRR22266027_rRNA.fastq --log /datafilepath/27_1.log`

### The output
```
2024-12-10 21:22:46 : INFO  Using high RECALL model
2024-12-10 21:22:46 : INFO  Log file: None
2024-12-10 21:22:46 : INFO  Classify reads with chunk size [1m256[0m
2024-12-10 21:22:46 : INFO  Writing output non-rRNA sequences into file: [94m/datafilepath/SRR22266027_rRNA.fastq[0m
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ribodetector/bin/ribodetector_cpu", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/ribodetector/lib/python3.8/site-packages/ribodetector/detect_cpu.py", line 822, in main
    seq_pred.detect()
  File "/opt/anaconda3/envs/ribodetector/lib/python3.8/site-packages/ribodetector/detect_cpu.py", line 599, in detect
    self.run_with_chunks()
  File "/opt/anaconda3/envs/ribodetector/lib/python3.8/site-packages/ribodetector/detect_cpu.py", line 500, in run_with_chunks
    for chunk in SeqEncoder.get_seq_chunks(*self.input,
  File "/opt/anaconda3/envs/ribodetector/lib/python3.8/site-packages/ribodetector/data_loader/seq_encoder.py", line 83, in get_seq_chunks
    seqs_chunk = list(islice(seq_iterator, chunk_size))
  File "/opt/anaconda3/envs/ribodetector/lib/python3.8/site-packages/ribodetector/data_loader/fastx_parser.py", line 21, in seq_parser
    if line[0] == '@' and record_line == 0:
IndexError: string index out of range
```

**Comment by dawnmy** [comment]
Could you show the first 8 lines in your /datafilepath/SRR22266027_rRNA.fastq file? It seems the fastq format was not correctly recognized by fastq parser.

**Comment by dawnmy** [comment]
@kinako0130 Have you managed to run the tool?

**Comment by kinako0130** [comment]
@dawnmy 
Thank you for your reply!
I apologize for my delayed response.

The error is still exist.
Here are the first 8 lines of my input file after trimmed sequences.

```
@SRR22266027.1 1 length=151
AAGATAGATTCCTGAAGGTCAGATTAGTGCGTCCAAATTATCATACCATTTTAGTAAGTTTTTGATATTNNACACAGNGCCTTCTGTTATAANTGAAATTTAAGAATAATTTGGGGGATTTCTTCTGCTTTTCCTTTCT
+
JFFFJJJ-<7F<<7-<FJ-F7AFJ-7<FF7-7---7<-<JJ-FJJ-7F-FAFJFJJJ7FJ--<FF<F--##A-<FFF#FJ-FAJJ777<AJ-#FA-J7-7AFJJAJJA--7FJJJJF7JJFJJJJJ<-<AAA-7AAJ-F
@SRR22266027.2 2 length=151
GCCCGCCCGGGAGAAGGACGGGGGGAGAGAGCACGAACGCGCCGAAGGGTATCTGGCTTCCTAGGCCCCGNGATTCGNCGAAAGCTGCGGCCNGCGGGCTGTAACACTCGGGGGGAGGTGGTTCGGCGCGCCCTGAGA
+
AA-AF<-AJF<-F--77777F<A-A7-7777--777-<-77-7AA-7<77<JJ-AAA-<-A--<-7A<AA#FJJFFF#AJ77<7FA7-A-7A#F7-A7A<AAA-7FJ7FF<FA-A7F7-FAAF-7FA<---AA7AAJF
```
But I noticed that if a FASTQ file without trimmed sequences is used, the command works correctly.
Therefore, I think I should remove ribosomal RNA first before performing adapter trimming, which might be a solution for my case.

**Comment by dawnmy** [comment]
Which trimming tool did you use? It seems some lines in the trimmed FASTQ file are empty, which is not acceptable for a valid FASTQ format.

**Comment by kinako0130** [comment]
I used cutadapt for adapter trimming.

**Comment by dawnmy** [comment]
The likely cause is: the FASTQ file contains blank lines (or is truncated). I will close this issue.
